### ISSUE TITLE
Control `targets` pipeline in detail

### ISSUE THREAD

**Issue by sigmafelix** [Spatiotemporal-Exposures-and-Toxicology/NRT-AP-Model#294]
- [ ] ~~Check if `targets` supports a "tolerance" option for ignoring minute changes in all or selected nodes~~
- [x] Make `_targets.R` succinct
- [x] Split `_targets.R` at base learner fitting (following parts will restored later)

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix  Can you articulate the kind of code or data edits that you expect may be needed for a "tolerance"? 

There is a lot to learn about targets including archetypes, branching, target_factories, that will hopefully provide us the nuance and detail we need. Lots to dig into though!

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix I do think our solution will be a combination of branching (I think static, but not positive yet) and function from archetypes, which does things like splitting, map(), etc. For example, we could treat each covariate calculation as a branch of the large calc_covariates.R -> buffer sizes could even be a branch (perhaps dynamic there)

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology Yes, there are lots of avenues I need to explore at. The pipeline now is just for a demonstration purposes, and we need to prune a group of links that are already controlled by targets, archetypes, and others.

**Comment by sigmafelix** [comment]
- [ ] `./tools` is dedicated to educational materials
- [ ] Move `./tools/pipeline` to `./inst/targets`
- [ ] Add `punchcard.csv` manual to README.md in `main`
- [ ] Change `punchcard.csv` name into the other
- [ ] Add tests for pipeline helper functions, then put the functions in `./R`
- [ ] `_targets.R` will be in `./inst/targets` (if this name is kept); installation script may be necessary
- [ ] Complete deprecation of `input/Rinput` anytime soon

**Comment by mitchellmanware** [comment]
@sigmafelix
Can you share the error? I have changes on `amadeus` branch which return `$time` for all time-oriented columns.

Is the pipeline example using the `amadeus` testdata or just functions?

**Comment by sigmafelix** [comment]
@mitchellmanware Thank you for checking in this issue. I found `calc_hms` in `main` returned a time column named `"date"`. I have a custom function for the pipeline to fix this, but it will be great to fix it in `amadeus`. By the way, I have several changes (i.e., adding ellipsis arguments in all `process_*` and `calc_*` function to enable argument injection) in `amadeus` functions as well. Could we push all changes to `main` in a day or two?

**Comment by mitchellmanware** [comment]
Yes, next few days is a good timeline for me. I just mentioned in another issue dialogue (https://github.com/NIEHS/amadeus/issues/45#issuecomment-2029690409) that new gridMET and TerraClimate functions and `calc_*`modularization are complete, but I am waiting until after PR to start OpenLandMap data source.
